### ISSUE TITLE
When row is empty get other irrelevant errors like type errors

### ISSUE THREAD

**Issue by rufuspollock** [okfn/tabular-validator-web#52]
An empty row should probably trump other errors rather than also showing errors about type errors (and in any case is an empty value a violation of type conditions ???)

Here's an example:

http://goodtables.okfnlabs.org/reports?data_url=https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/252886/July_2013_GPC_Transparency_Data.csv&format=CSV&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json

**Comment by georgiana-b** [comment]
I can't replicate the  type errors. I get only: 
- `Incorrect Headers :  Missing required column headings: Amount, Transaction number, Expense type, Date, Department family, Entity, Expense area, Description, Supplier.`  (which is normal because these fields are required in the schema)
- `Defective Row :  The row dimensions are incorrect compared to headers.` (which apparently shouldn't be there and I opened frictionlessdata/goodtables#98 for further investigation.)

**Comment by roll** [comment]
Please use https://try.goodtables.io
