### ISSUE TITLE
Validation of empty Number, Date fields flagged as bad formats

### ISSUE THREAD

**Issue by harrisj** [okfn/tabular-validator-web#53]
If required is set to false, these should be treated as nil values and not be flagged as format violations

**Comment by georgiana-b** [comment]
This issue is the same as frictionlessdata/goodtables#58 and is now fixed as seen [in this example](http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fgist.githubusercontent.com%2Fgeorgiana-b%2F4f55b396b72213748b869d29c3418bd5%2Fraw%2Fe1ef977a49396845fd61e6a990f4f434434f227c%2Fpersons.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgist.githubusercontent.com%2Fgeorgiana-b%2F4f55b396b72213748b869d29c3418bd5%2Fraw%2Fe1ef977a49396845fd61e6a990f4f434434f227c%2Fperson_schema.json).

**Comment by pwalsh** [comment]
FIXED.
